apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloapp
  name: helloapp
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: helloapp
  type: NodePort